changelog:
  exclude:
    labels:
      - internal
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features
      labels:
        - feature
    - title: Fixes
      labels:
        - fix
